services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_HigherOrLower
    env_file:
      - ./.env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_HigherOrLower
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
